#!/bin/bash

if [ $# -gt 1 ]; then
    echo "It accepts only one argument, which is the option of execution."
    exit 1
elif [ $# -eq 1 ] && [ $1 != "exec" ]; then
    echo "Wrong argument. It only accepts 'exec' as an argument."
    exit 1
fi

docker build -t backend:1.0 .
docker run -d -p 5100:5000 --name backend backend:1.0

if [ $# -eq 1 ] && [ $1 == "exec" ]; then
    docker exec -it backend bash
fi